In [1]:
import polars as pl

DATASET_NAME_PERFIX = "dataset_255w_"
TRAIN_SIZE = 0.8
VAL_SIZE = 0.1
TEST_SIZE = 0.1

df_lehner = pl.read_csv(
    "lehner_dataset_with_sequences_normalized.csv",
)
df_lehner = df_lehner.drop_nulls(
    subset=["original_seq_full", "mut_type", "mutated_seq_full", "normalized_fitness_sigmoid"])

df_lehner = df_lehner.with_columns(
    [
        pl.lit("lehner").alias("data_source"),
    ]
)

df_lehner = df_lehner.rename({"normalized_fitness_sigmoid": "target"})

df_lehner = df_lehner.select(["original_seq_full", "mutated_seq_full", "mut_type", "target", "reverse", "data_source"])

df_lehner

shape: (1_116_004, 6)
┌─────────────────────────┬─────────────────────────┬──────────┬───────────┬─────────┬─────────────┐
│ original_seq_full       ┆ mutated_seq_full        ┆ mut_type ┆ target    ┆ reverse ┆ data_source │
│ ---                     ┆ ---                     ┆ ---      ┆ ---       ┆ ---     ┆ ---         │
│ str                     ┆ str                     ┆ str      ┆ f64       ┆ bool    ┆ str         │
╞═════════════════════════╪═════════════════════════╪══════════╪═══════════╪═════════╪═════════════╡
│ M*IFVKTLMGKTITLEVELSDTI ┆ MQIFVKTLMGKTITLEVELSDTI ┆ Q2*      ┆ 0.342301  ┆ true    ┆ lehner      │
│ DNVKAKI…                ┆ DNVKAKI…                ┆          ┆           ┆         ┆             │
│ MAIFVKTLMGKTITLEVELSDTI ┆ MQIFVKTLMGKTITLEVELSDTI ┆ Q2A      ┆ 0.121678  ┆ true    ┆ lehner      │
│ DNVKAKI…                ┆ DNVKAKI…                ┆          ┆           ┆         ┆             │
│ MCIFVKTLMGKTITLEVELSDTI ┆ MQIFVKTLMGKTITLEVELSDTI ┆ Q2C      ┆ 0.044935  ┆ true    ┆ lehner      │
│ DNVKAKI…                ┆ DNVKAKI…                ┆          ┆           ┆         ┆             │
│ MDIFVKTLMGKTITLEVELSDTI ┆ MQIFVKTLMGKTITLEVELSDTI ┆ Q2D      ┆ 0.11189   ┆ true    ┆ lehner      │
│ DNVKAKI…                ┆ DNVKAKI…                ┆          ┆           ┆         ┆             │
│ MEIFVKTLMGKTITLEVELSDTI ┆ MQIFVKTLMGKTITLEVELSDTI ┆ Q2E      ┆ -0.162632 ┆ true    ┆ lehner      │
│ DNVKAKI…                ┆ DNVKAKI…                ┆          ┆           ┆         ┆             │
│ …                       ┆ …                       ┆ …        ┆ …         ┆ …       ┆ …           │
│ MGNEASLEGEGLPEGLAAAAAAG ┆ MGNEASLEGEGLPEGLAAAAAAG ┆ V1059C   ┆ -0.45026  ┆ false   ┆ lehner      │
│ GGASGAG…                ┆ GGASGAG…                ┆          ┆           ┆         ┆             │
│ MGNEASLEGEGLPEGLAAAAAAG ┆ MGNEASLEGEGLPEGLAAAAAAG ┆ W1059C   ┆ -0.374472 ┆ false   ┆ lehner      │
│ GGASGAG…                ┆ GGASGAG…                ┆          ┆           ┆         ┆             │
│ MGNEASLEGEGLPEGLAAAAAAG ┆ MGNEASLEGEGLPEGLAAAAAAG ┆ Y1059C   ┆ -0.462593 ┆ false   ┆ lehner      │
│ GGASGAG…                ┆ GGASGAG…                ┆          ┆           ┆         ┆             │
│ MGNEASLEGEGLPEGLAAAAAAG ┆ MGNEASLEGEGLPEGLAAAAAAG ┆ V1058T   ┆ -0.087532 ┆ false   ┆ lehner      │
│ GGASGAG…                ┆ GGASGAG…                ┆          ┆           ┆         ┆             │
│ MGNEASLEGEGLPEGLAAAAAAG ┆ MGNEASLEGEGLPEGLAAAAAAG ┆ W1058T   ┆ -0.220831 ┆ false   ┆ lehner      │
│ GGASGAG…                ┆ GGASGAG…                ┆          ┆           ┆         ┆             │
└─────────────────────────┴─────────────────────────┴──────────┴───────────┴─────────┴─────────────┘

In [2]:
df_megascale = pl.read_csv(
    "megascale_dataset_with_ddg_normalized.csv",
)

df_megascale = df_megascale.drop_nulls(
    subset=["original_seq_full", "mut_type", "mutated_seq_full", "normalized_ddG_sigmoid"])

df_megascale = df_megascale.with_columns(
    [
        pl.lit("megascale").alias("data_source"),
    ]
)

df_megascale = df_megascale.rename({"normalized_ddG_sigmoid": "target"})

df_megascale = df_megascale.select(["original_seq_full", "mutated_seq_full", "mut_type", "target", "reverse", "data_source"])

df_megascale

shape: (833_828, 6)
┌─────────────────────────┬────────────────────────┬───────────┬───────────┬─────────┬─────────────┐
│ original_seq_full       ┆ mutated_seq_full       ┆ mut_type  ┆ target    ┆ reverse ┆ data_source │
│ ---                     ┆ ---                    ┆ ---       ┆ ---       ┆ ---     ┆ ---         │
│ str                     ┆ str                    ┆ str       ┆ f64       ┆ bool    ┆ str         │
╞═════════════════════════╪════════════════════════╪═══════════╪═══════════╪═════════╪═════════════╡
│ SAGGTYTWNTKEEAKQAFKELLK ┆ SAGGTYTWNTKEEAKQAFKELL ┆ R22P      ┆ -0.209184 ┆ false   ┆ megascale   │
│ EKRVPSN…                ┆ KEKPVPSN…              ┆           ┆           ┆         ┆             │
│ SAGGSAGGSAGGHEITLHINGRR ┆ SAGGSAGGSAGGHEITLHINGR ┆ R17T      ┆ -0.110833 ┆ false   ┆ megascale   │
│ VKLRFRD…                ┆ RVKLRFTD…              ┆           ┆           ┆         ┆             │
│ SAGGSAGGSKDPKFEAAYDFPGS ┆ SAGGSAGGSKDPKFEAAMDFPG ┆ Y9M:K24Q  ┆ -0.151356 ┆ false   ┆ megascale   │
│ GSSSELP…                ┆ SGSSSELP…              ┆           ┆           ┆         ┆             │
│ SAGGNKASVVANQLIPINTALTL ┆ SAGGNKASVVANQLIPINTALT ┆ K39N      ┆ -0.038819 ┆ false   ┆ megascale   │
│ IMMKAEV…                ┆ LIMMKAEV…              ┆           ┆           ┆         ┆             │
│ SAGGSAGWVPTKREEKYGVAFYN ┆ SAGGSAGWVPTKREEKYGVAFY ┆ D31M:T47G ┆ -0.187832 ┆ false   ┆ megascale   │
│ YDARGAD…                ┆ NYDARGAD…              ┆           ┆           ┆         ┆             │
│ …                       ┆ …                      ┆ …         ┆ …         ┆ …       ┆ …           │
│ SAGGNQASVVANQLIPINTALTL ┆ SAGGNQASVVANQLIPINTALT ┆ V26E      ┆ -0.13243  ┆ true    ┆ megascale   │
│ VMMRSEE…                ┆ LVMMRSEV…              ┆           ┆           ┆         ┆             │
│ SAGGSAGGSAQGDIVVALYPEDG ┆ SAGGSAGGSAQGDIVVALYPYD ┆ Y11E:Y54I ┆ 0.604106  ┆ true    ┆ megascale   │
│ IHPDDLS…                ┆ GIHPDDLS…              ┆           ┆           ┆         ┆             │
│ SAGGSAGGMTYKLILNGKTLKGE ┆ SAGGSAGGMTYKLILNGKTLKG ┆ D47K      ┆ 0.091188  ┆ true    ┆ megascale   │
│ TTTEAVD…                ┆ ETTTEAVD…              ┆           ┆           ┆         ┆             │
│ GSQPHIGNTTFTFDNPEKAQKYA ┆ GSQVHIGNTTFTFDNPEKAQKY ┆ V3P       ┆ 0.1783    ┆ true    ┆ megascale   │
│ EKYAKKK…                ┆ AEKYAKKK…              ┆           ┆           ┆         ┆             │
│ SAGGSAGGMVQRGSKVRILRPES ┆ SAGGSAGGMVQRGSKVRILRPE ┆ E41P:K42M ┆ 0.249009  ┆ true    ┆ megascale   │
│ YWFQDVG…                ┆ SYWFQDVG…              ┆           ┆           ┆         ┆             │
└─────────────────────────┴────────────────────────┴───────────┴───────────┴─────────┴─────────────┘

In [4]:
df_255 = pl.concat([df_megascale, df_lehner])

df_255.filter(pl.col('original_seq_full') != pl.col('mutated_seq_full'))

shape: (1_949_832, 6)
┌─────────────────────────┬────────────────────────┬───────────┬───────────┬─────────┬─────────────┐
│ original_seq_full       ┆ mutated_seq_full       ┆ mut_type  ┆ target    ┆ reverse ┆ data_source │
│ ---                     ┆ ---                    ┆ ---       ┆ ---       ┆ ---     ┆ ---         │
│ str                     ┆ str                    ┆ str       ┆ f64       ┆ bool    ┆ str         │
╞═════════════════════════╪════════════════════════╪═══════════╪═══════════╪═════════╪═════════════╡
│ SAGGTYTWNTKEEAKQAFKELLK ┆ SAGGTYTWNTKEEAKQAFKELL ┆ R22P      ┆ -0.209184 ┆ false   ┆ megascale   │
│ EKRVPSN…                ┆ KEKPVPSN…              ┆           ┆           ┆         ┆             │
│ SAGGSAGGSAGGHEITLHINGRR ┆ SAGGSAGGSAGGHEITLHINGR ┆ R17T      ┆ -0.110833 ┆ false   ┆ megascale   │
│ VKLRFRD…                ┆ RVKLRFTD…              ┆           ┆           ┆         ┆             │
│ SAGGSAGGSKDPKFEAAYDFPGS ┆ SAGGSAGGSKDPKFEAAMDFPG ┆ Y9M:K24Q  ┆ -0.151356 ┆ false   ┆ megascale   │
│ GSSSELP…                ┆ SGSSSELP…              ┆           ┆           ┆         ┆             │
│ SAGGNKASVVANQLIPINTALTL ┆ SAGGNKASVVANQLIPINTALT ┆ K39N      ┆ -0.038819 ┆ false   ┆ megascale   │
│ IMMKAEV…                ┆ LIMMKAEV…              ┆           ┆           ┆         ┆             │
│ SAGGSAGWVPTKREEKYGVAFYN ┆ SAGGSAGWVPTKREEKYGVAFY ┆ D31M:T47G ┆ -0.187832 ┆ false   ┆ megascale   │
│ YDARGAD…                ┆ NYDARGAD…              ┆           ┆           ┆         ┆             │
│ …                       ┆ …                      ┆ …         ┆ …         ┆ …       ┆ …           │
│ MGNEASLEGEGLPEGLAAAAAAG ┆ MGNEASLEGEGLPEGLAAAAAA ┆ V1059C    ┆ -0.45026  ┆ false   ┆ lehner      │
│ GGASGAG…                ┆ GGGASGAG…              ┆           ┆           ┆         ┆             │
│ MGNEASLEGEGLPEGLAAAAAAG ┆ MGNEASLEGEGLPEGLAAAAAA ┆ W1059C    ┆ -0.374472 ┆ false   ┆ lehner      │
│ GGASGAG…                ┆ GGGASGAG…              ┆           ┆           ┆         ┆             │
│ MGNEASLEGEGLPEGLAAAAAAG ┆ MGNEASLEGEGLPEGLAAAAAA ┆ Y1059C    ┆ -0.462593 ┆ false   ┆ lehner      │
│ GGASGAG…                ┆ GGGASGAG…              ┆           ┆           ┆         ┆             │
│ MGNEASLEGEGLPEGLAAAAAAG ┆ MGNEASLEGEGLPEGLAAAAAA ┆ V1058T    ┆ -0.087532 ┆ false   ┆ lehner      │
│ GGASGAG…                ┆ GGGASGAG…              ┆           ┆           ┆         ┆             │
│ MGNEASLEGEGLPEGLAAAAAAG ┆ MGNEASLEGEGLPEGLAAAAAA ┆ W1058T    ┆ -0.220831 ┆ false   ┆ lehner      │
│ GGASGAG…                ┆ GGGASGAG…              ┆           ┆           ┆         ┆             │
└─────────────────────────┴────────────────────────┴───────────┴───────────┴─────────┴─────────────┘

In [5]:
import re
# Add sub_sequence column (21 aa from 'position')


WINDOW = 255
HALF = WINDOW // 2  # 256


def get_fragments_from_struct(row_dict: dict) -> dict:
    """
    Funkce extrahuje fragmenty o velikosti WINDOW.
    Přijímá slovník a vrací slovník s novými hodnotami.
    """
    mut_type = row_dict["mut_type"]
    original_seq = row_dict["original_seq_full"]
    mutated_seq = row_dict["mutated_seq_full"]

    # Získání první číselné hodnoty ze sloupce 'mut_type'
    match = re.search(r'\d+', mut_type)
    if not match:
        return {"fragment_255_mut": None, "fragment_255_org": None}

    # Pozice je 1-based, pro index v Pythonu odečteme 1
    center_index = int(match.group(0)) - 1
    seq_len = len(original_seq)

    # Výpočet počátečního a koncového indexu
    start = center_index - HALF
    end = start + WINDOW

    # Ošetření okrajů sekvence
    if start < 0:
        start = 0
        end = WINDOW
    if end > seq_len:
        end = seq_len
        start = seq_len - WINDOW
    if start < 0: # Zajištění pro sekvence kratší než WINDOW
        start = 0

    # Extrakce fragmentů
    org_fragment = original_seq[start:end]
    mut_fragment = mutated_seq[start:end]

    # Funkce musí vrátit slovník s názvy budoucích sloupců
    return {"fragment_255_mut": mut_fragment, "fragment_255_org": org_fragment}

# Aplikace funkce na DataFrame
df_255 = df_255.with_columns(
    # 1. Seskupíme potřebné sloupce do dočasné struktury
    pl.struct(["mut_type", "original_seq_full", "mutated_seq_full"])
    # 2. Aplikujeme funkci na tuto strukturu.
    #    Je nutné specifikovat návratový typ pro optimalizaci.
    .map_elements(
        get_fragments_from_struct,
        return_dtype=pl.Struct([
            pl.Field("fragment_255_mut", pl.String),
            pl.Field("fragment_255_org", pl.String),
        ])
    )
    # 3. Dáme výsledné struktuře dočasný název
    .alias("fragments_struct")
).unnest("fragments_struct") # 4. Rozbalíme strukturu do finálních sloupců



df_255

shape: (1_949_832, 8)
┌────────────┬────────────┬───────────┬───────────┬─────────┬────────────┬────────────┬────────────┐
│ original_s ┆ mutated_se ┆ mut_type  ┆ target    ┆ reverse ┆ data_sourc ┆ fragment_2 ┆ fragment_2 │
│ eq_full    ┆ q_full     ┆ ---       ┆ ---       ┆ ---     ┆ e          ┆ 55_mut     ┆ 55_org     │
│ ---        ┆ ---        ┆ str       ┆ f64       ┆ bool    ┆ ---        ┆ ---        ┆ ---        │
│ str        ┆ str        ┆           ┆           ┆         ┆ str        ┆ str        ┆ str        │
╞════════════╪════════════╪═══════════╪═══════════╪═════════╪════════════╪════════════╪════════════╡
│ SAGGTYTWNT ┆ SAGGTYTWNT ┆ R22P      ┆ -0.209184 ┆ false   ┆ megascale  ┆ SAGGTYTWNT ┆ SAGGTYTWNT │
│ KEEAKQAFKE ┆ KEEAKQAFKE ┆           ┆           ┆         ┆            ┆ KEEAKQAFKE ┆ KEEAKQAFKE │
│ LLKEKRVPSN ┆ LLKEKPVPSN ┆           ┆           ┆         ┆            ┆ LLKEKPVPSN ┆ LLKEKRVPSN │
│ …          ┆ …          ┆           ┆           ┆         ┆            ┆ …          ┆ …          │
│ SAGGSAGGSA ┆ SAGGSAGGSA ┆ R17T      ┆ -0.110833 ┆ false   ┆ megascale  ┆ SAGGSAGGSA ┆ SAGGSAGGSA │
│ GGHEITLHIN ┆ GGHEITLHIN ┆           ┆           ┆         ┆            ┆ GGHEITLHIN ┆ GGHEITLHIN │
│ GRRVKLRFRD ┆ GRRVKLRFTD ┆           ┆           ┆         ┆            ┆ GRRVKLRFTD ┆ GRRVKLRFRD │
│ …          ┆ …          ┆           ┆           ┆         ┆            ┆ …          ┆ …          │
│ SAGGSAGGSK ┆ SAGGSAGGSK ┆ Y9M:K24Q  ┆ -0.151356 ┆ false   ┆ megascale  ┆ SAGGSAGGSK ┆ SAGGSAGGSK │
│ DPKFEAAYDF ┆ DPKFEAAMDF ┆           ┆           ┆         ┆            ┆ DPKFEAAMDF ┆ DPKFEAAYDF │
│ PGSGSSSELP ┆ PGSGSSSELP ┆           ┆           ┆         ┆            ┆ PGSGSSSELP ┆ PGSGSSSELP │
│ …          ┆ …          ┆           ┆           ┆         ┆            ┆ …          ┆ …          │
│ SAGGNKASVV ┆ SAGGNKASVV ┆ K39N      ┆ -0.038819 ┆ false   ┆ megascale  ┆ SAGGNKASVV ┆ SAGGNKASVV │
│ ANQLIPINTA ┆ ANQLIPINTA ┆           ┆           ┆         ┆            ┆ ANQLIPINTA ┆ ANQLIPINTA │
│ LTLIMMKAEV ┆ LTLIMMKAEV ┆           ┆           ┆         ┆            ┆ LTLIMMKAEV ┆ LTLIMMKAEV │
│ …          ┆ …          ┆           ┆           ┆         ┆            ┆ …          ┆ …          │
│ SAGGSAGWVP ┆ SAGGSAGWVP ┆ D31M:T47G ┆ -0.187832 ┆ false   ┆ megascale  ┆ SAGGSAGWVP ┆ SAGGSAGWVP │
│ TKREEKYGVA ┆ TKREEKYGVA ┆           ┆           ┆         ┆            ┆ TKREEKYGVA ┆ TKREEKYGVA │
│ FYNYDARGAD ┆ FYNYDARGAD ┆           ┆           ┆         ┆            ┆ FYNYDARGAD ┆ FYNYDARGAD │
│ …          ┆ …          ┆           ┆           ┆         ┆            ┆ …          ┆ …          │
│ …          ┆ …          ┆ …         ┆ …         ┆ …       ┆ …          ┆ …          ┆ …          │
│ MGNEASLEGE ┆ MGNEASLEGE ┆ V1059C    ┆ -0.45026  ┆ false   ┆ lehner     ┆ FGFGASIFSQ ┆ FGFGASIFSQ │
│ GLPEGLAAAA ┆ GLPEGLAAAA ┆           ┆           ┆         ┆            ┆ ASNLISTAGQ ┆ ASNLISTAGQ │
│ AAGGGASGAG ┆ AAGGGASGAG ┆           ┆           ┆         ┆            ┆ PGPHSQSGPG ┆ PGPHSQSGPG │
│ …          ┆ …          ┆           ┆           ┆         ┆            ┆ …          ┆ …          │
│ MGNEASLEGE ┆ MGNEASLEGE ┆ W1059C    ┆ -0.374472 ┆ false   ┆ lehner     ┆ FGFGASIFSQ ┆ FGFGASIFSQ │
│ GLPEGLAAAA ┆ GLPEGLAAAA ┆           ┆           ┆         ┆            ┆ ASNLISTAGQ ┆ ASNLISTAGQ │
│ AAGGGASGAG ┆ AAGGGASGAG ┆           ┆           ┆         ┆            ┆ PGPHSQSGPG ┆ PGPHSQSGPG │
│ …          ┆ …          ┆           ┆           ┆         ┆            ┆ …          ┆ …          │
│ MGNEASLEGE ┆ MGNEASLEGE ┆ Y1059C    ┆ -0.462593 ┆ false   ┆ lehner     ┆ FGFGASIFSQ ┆ FGFGASIFSQ │
│ GLPEGLAAAA ┆ GLPEGLAAAA ┆           ┆           ┆         ┆            ┆ ASNLISTAGQ ┆ ASNLISTAGQ │
│ AAGGGASGAG ┆ AAGGGASGAG ┆           ┆           ┆         ┆            ┆ PGPHSQSGPG ┆ PGPHSQSGPG │
│ …          ┆ …          ┆           ┆           ┆         ┆            ┆ …          ┆ …          │
│ MGNEASLEGE ┆ MGNEASLEGE ┆ V1058T    ┆ -0.087532 ┆ false   ┆ lehner     ┆ LFGFGASIFS ┆ LFGFGASIFS │
│ GLPEGLAAAA ┆ GLPEGLAAAA ┆           ┆           ┆         ┆            ┆ QASNLISTAG ┆ QASNLISTAG │
│ AAGGGASGAG ┆ AAGGGASGAG ┆           ┆           ┆         ┆            ┆ QPGPHSQSGP ┆ QPGPHSQSGP │
│ …          ┆ …          ┆           ┆           ┆         ┆            ┆ …          ┆ …          │
│ MGNEASLEGE ┆ MGNEASLEGE ┆ W1058T    ┆ -0.220831 ┆ false   ┆ lehner     ┆ LFGFGASIFS ┆ LFGFGASIFS │
│ GLPEGLAAAA ┆ GLPEGLAAAA ┆           ┆           ┆         ┆            ┆ QASNLISTAG ┆ QASNLISTAG │
│ AAGGGASGAG ┆ AAGGGASGAG ┆           ┆           ┆         ┆            ┆ QPGPHSQSGP ┆ QPGPHSQSGP │
│ …          ┆ …          ┆           ┆           ┆         ┆            ┆ …          ┆ …          │
└────────────┴────────────┴───────────┴───────────┴─────────┴────────────┴────────────┴────────────┘

In [8]:
# check:

df_megascale.filter(pl.col('original_seq_full') != pl.col('mutated_seq_full'))

print(f"The original and mutated seqence are same lenght? {len(df_255.filter(pl.col("fragment_255_mut").str.len_chars() == pl.col("fragment_255_org").str.len_chars()))}  vs  {len(df_255)} {len(df_255) == len(df_255.filter(pl.col("fragment_255_mut").str.len_chars() == pl.col("fragment_255_org").str.len_chars()))} ")

# checkc of the original seq is same as  original seq in the df

print(f"Are the mutated sequences different from the original sequences? {len(df_255.filter(pl.col('original_seq_full') != pl.col('mutated_seq_full')))} vs {len(df_255)} {len(df_255.filter(pl.col('original_seq_full') != pl.col('mutated_seq_full'))) == len(df_255)}")

The original and mutated seqence are same lenght? 1949832  vs  1949832 True
Are the mutated sequences different from the original sequences? 1949832 vs 1949832 True

In [10]:
# First, we shuffle the data randomly
df_shuffled = df_255.sample(fraction=1, shuffle=True, seed=123)  # Using a seed for reproducibility

# Get the total number of rows
n_rows = len(df_shuffled)

# Calculate the sizes of each set (80% training, 10% validation, 10% testing)
train_size = int(TRAIN_SIZE * n_rows)
val_size = int(VAL_SIZE * n_rows)
# The remainder will be the testing set

# Split the dataframe into three parts
train_df = df_shuffled.slice(0, train_size)
val_df = df_shuffled.slice(train_size, val_size)
test_df = df_shuffled.slice(train_size + val_size)  # to the end

test_df_noreverse = test_df.filter(pl.col("reverse") == False)

# Save each dataset to a separate CSV file
train_df.write_csv(f"{DATASET_NAME_PERFIX}train.csv")
val_df.write_csv(f"{DATASET_NAME_PERFIX}validation.csv")
test_df.write_csv(f"{DATASET_NAME_PERFIX}test.csv")
test_df_noreverse.write_csv(f"{DATASET_NAME_PERFIX}_noreverse_test.csv")

print(f"Datasets were successfully created and saved:")
print(f"- Training set (training_dataset.csv): {len(train_df)} rows")
print(f"- Validation set (validation_dataset.csv): {len(val_df)} rows")
print(f"- Testing set (testing_dataset.csv): {len(test_df)} rows")
print(f"- Testing set without reverse mutations (testing_noreverse_dataset.csv): {len(test_df_noreverse)} rows")

Datasets were successfully created and saved:
- Training set (training_dataset.csv): 1559865 rows
- Validation set (validation_dataset.csv): 194983 rows
- Testing set (testing_dataset.csv): 194984 rows
- Testing set without reverse mutations (testing_noreverse_dataset.csv): 97656 rows

In [18]:
train_df

shape: (1_559_865, 8)
┌─────────────┬────────────┬──────────┬───────────┬─────────┬────────────┬────────────┬────────────┐
│ original_se ┆ mutated_se ┆ mut_type ┆ target    ┆ reverse ┆ data_sourc ┆ fragment_2 ┆ fragment_2 │
│ q_full      ┆ q_full     ┆ ---      ┆ ---       ┆ ---     ┆ e          ┆ 55_mut     ┆ 55_org     │
│ ---         ┆ ---        ┆ str      ┆ f64       ┆ bool    ┆ ---        ┆ ---        ┆ ---        │
│ str         ┆ str        ┆          ┆           ┆         ┆ str        ┆ str        ┆ str        │
╞═════════════╪════════════╪══════════╪═══════════╪═════════╪════════════╪════════════╪════════════╡
│ MNGEAICSALP ┆ MNGEAICSAL ┆ T486K    ┆ -0.31997  ┆ false   ┆ lehner     ┆ CLIELEPVLR ┆ CLIELEPVLR │
│ TIPYHKLADLR ┆ PTIPYHKLAD ┆          ┆           ┆         ┆            ┆ TFEEITFLEA ┆ TFEEITFLEA │
│ YLSRGASG…   ┆ LRYLSRGASG ┆          ┆           ┆         ┆            ┆ VIQLKKTKLQ ┆ VIQLKKTKLQ │
│             ┆ …          ┆          ┆           ┆         ┆            ┆ …          ┆ …          │
│ MKAADTVILWA ┆ MKAADTVILW ┆ F390E    ┆ -0.070308 ┆ false   ┆ lehner     ┆ GKGPGHKRRS ┆ GKGPGHKRRS │
│ RSKNDQLRISF ┆ ARSKNDQLRI ┆          ┆           ┆         ┆            ┆ KSPRVPDGRK ┆ KSPRVPDGRK │
│ PPGLCWGD…   ┆ SFPPGLCWGD ┆          ┆           ┆         ┆            ┆ KLRGKKMAPL ┆ KLRGKKMAPL │
│             ┆ …          ┆          ┆           ┆         ┆            ┆ …          ┆ …          │
│ SAGGMQGVVKV ┆ SAGGMQGVVK ┆ A42Y     ┆ 0.185307  ┆ false   ┆ megascale  ┆ SAGGMQGVVK ┆ SAGGMQGVVK │
│ NSALNMRSGPG ┆ VNSALNMRSG ┆          ┆           ┆         ┆            ┆ VNSALNMRSG ┆ VNSALNMRSG │
│ SNYGVIGT…   ┆ PGSNYGVIGT ┆          ┆           ┆         ┆            ┆ PGSNYGVIGT ┆ PGSNYGVIGT │
│             ┆ …          ┆          ┆           ┆         ┆            ┆ …          ┆ …          │
│ MPPLKSPAAFH ┆ MPPLKSPAAF ┆ K356V    ┆ 0.062392  ┆ true    ┆ lehner     ┆ LKPKVKKLKY ┆ LKPKVKKLKY │
│ EQRRSLERART ┆ HEQRRSLERA ┆          ┆           ┆         ┆            ┆ HQYIPPDQKQ ┆ HQYIPPDQKQ │
│ EDYLKRKI…   ┆ RTEDYLKRKI ┆          ┆           ┆         ┆            ┆ DRGAPPMDSS ┆ DRGAPPMDSS │
│             ┆ …          ┆          ┆           ┆         ┆            ┆ …          ┆ …          │
│ SAGGSAGGTVK ┆ SAGGSAGGTV ┆ G42T     ┆ 0.293882  ┆ true    ┆ megascale  ┆ SAGGSAGGTV ┆ SAGGSAGGTV │
│ FKYKGEEKQVD ┆ KFKYKGEEKQ ┆          ┆           ┆         ┆            ┆ KFKYKGEEKQ ┆ KFKYKGEEKQ │
│ ISKIKKVW…   ┆ VDISKIKKVW ┆          ┆           ┆         ┆            ┆ VDISKIKKVW ┆ VDISKIKKVW │
│             ┆ …          ┆          ┆           ┆         ┆            ┆ …          ┆ …          │
│ …           ┆ …          ┆ …        ┆ …         ┆ …       ┆ …          ┆ …          ┆ …          │
│ GDEDSERELEK ┆ GDEDSERELE ┆ K41F     ┆ 0.014103  ┆ false   ┆ megascale  ┆ GDEDSERELE ┆ GDEDSERELE │
│ LRKNNASKEEI ┆ KLRKNNASKE ┆          ┆           ┆         ┆            ┆ KLRKNNASKE ┆ KLRKNNASKE │
│ KEVLKRLG…   ┆ EIKEVLKRLG ┆          ┆           ┆         ┆            ┆ EIKEVLKRLG ┆ EIKEVLKRLG │
│             ┆ …          ┆          ┆           ┆         ┆            ┆ …          ┆ …          │
│ MDLTAIYESLL ┆ MDLTAIYESL ┆ D107E    ┆ -0.233018 ┆ false   ┆ lehner     ┆ MDLTAIYESL ┆ MDLTAIYESL │
│ SLSPDVPVPSD ┆ LSLSPDVPVP ┆          ┆           ┆         ┆            ┆ LSLSPDVPVP ┆ LSLSPDVPVP │
│ HGGTESSP…   ┆ SDHGGTESSP ┆          ┆           ┆         ┆            ┆ SDHGGTESSP ┆ SDHGGTESSP │
│             ┆ …          ┆          ┆           ┆         ┆            ┆ …          ┆ …          │
│ SAGGSAGGNQA ┆ SAGGSAGGNQ ┆ S4I:T54V ┆ 0.791514  ┆ true    ┆ megascale  ┆ SAGGSAGGNQ ┆ SAGGSAGGNQ │
│ IVVANQLIPIQ ┆ ASVVANQLIP ┆          ┆           ┆         ┆            ┆ ASVVANQLIP ┆ AIVVANQLIP │
│ TALTLVMM…   ┆ IQTALTLVMM ┆          ┆           ┆         ┆            ┆ IQTALTLVMM ┆ IQTALTLVMM │
│             ┆ …          ┆          ┆           ┆         ┆            ┆ …          ┆ …          │
│ SAGGSSISSRV ┆ SAGGSSISSR ┆ G37Q     ┆ 0.18964   ┆ true    ┆ megascale  ┆ SAGGSSISSR ┆ SAGGSSISSR │
│ KSKRIQLGLNQ ┆ VKSKRIQLGL ┆          ┆           ┆         ┆            ┆ VKSKRIQLGL ┆ VKSKRIQLGL │
│ AELAQKVG…   ┆ NQAELAQKVG ┆          ┆           ┆         ┆            ┆ NQAELAQKVG ┆ NQAELAQKVG │
│             ┆ …          ┆          ┆           ┆         ┆            ┆ …          ┆ …          │
│ LQAFIKTLTGK ┆ LQAFIKTLTG ┆ G35D     ┆ 0.165819  ┆ true    ┆ megascale  ┆ LQAFIKTLTG ┆ LQAFIKTLTG │
│ TFTVEMEPSDT ┆ KTFTVEMEPS ┆          ┆           ┆         ┆            ┆ KTFTVEMEPS ┆ KTFTVEMEPS │
│ IENLKAKI…   ┆ DTIENLKAKI ┆          ┆           ┆         ┆            ┆ DTIENLKAKI ┆ DTIENLKAKI │
│             ┆ …          ┆          ┆           ┆         ┆            ┆ …          ┆ …          │
└─────────────┴────────────┴──────────┴───────────┴─────────┴────────────┴────────────┴────────────┘

In [19]:
extract_fragment(
    "MQIFVKTLMGKTITLEVELSDTIDNVKAKIQDKEGIPPDQQRLIFAGKQLEDGRTLSDYNIQKESTLHLVLRLRGGAKKRKKKSYTTPRKNKHKRKKVKLALLKYYKVDENGKISCLHRECPSDECGAGVFMASHFDRHYCGKCCLTYCFNKPEDK", )

NameError: name 'extract_fragment' is not defined