In [1]:
import polars as pl

df = pl.read_parquet(
    "datasets/megascale_dataset_with_ddg.parquet",
)
df

shape: (833_828, 7)
┌────────────────────┬───────────────────┬───────────┬───────────┬───────────┬───────────┬─────────┐
│ original_seq_full  ┆ mutated_seq_full  ┆ deltaG    ┆ deltaG_wt ┆ ddG       ┆ mut_type  ┆ reverse │
│ ---                ┆ ---               ┆ ---       ┆ ---       ┆ ---       ┆ ---       ┆ ---     │
│ str                ┆ str               ┆ f64       ┆ f64       ┆ f64       ┆ str       ┆ bool    │
╞════════════════════╪═══════════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═════════╡
│ GGGLPEGWEMRFTVDGIP ┆ GGGTPEGWEMRFTVDGI ┆ -0.369388 ┆ 1.362971  ┆ -1.732359 ┆ L4T       ┆ false   │
│ YFVDHNRRTTTY…      ┆ PYFVDHNRRTTTY…    ┆           ┆           ┆           ┆           ┆         │
│ SAGGSAGGSAGGVDNKFN ┆ SAGGSAGGSAGGVDNKF ┆ 3.299296  ┆ 3.642546  ┆ -0.34325  ┆ N33E      ┆ false   │
│ KEQQNAFYEILH…      ┆ NKEQQNAFYEILH…    ┆           ┆           ┆           ┆           ┆         │
│ SAGMEQATVKWFNAEKGF ┆ SAGMEQATVKWFNAEKG ┆ -0.116898 ┆ 1.873137  ┆ -1.990035 ┆ Q62D      ┆ false   │
│ GFIERENGDDVF…      ┆ FGFIERENGDDVF…    ┆           ┆           ┆           ┆           ┆         │
│ SAGGSAGGNQASVVANQL ┆ SAGGSAGGNQASVVANQ ┆ 6.390221  ┆ 5.703114  ┆ 0.687108  ┆ I40L:L48Y ┆ false   │
│ IPINTALTLVMM…      ┆ LIPINTALTLVMM…    ┆           ┆           ┆           ┆           ┆         │
│ SAGGSAGGTVKFKYKGEE ┆ SAGGSAGGTVKFKYKGE ┆ 4.645758  ┆ 4.220052  ┆ 0.425707  ┆ V52I      ┆ false   │
│ KQVDISKIKKVW…      ┆ EKQVDISKIKKVW…    ┆           ┆           ┆           ┆           ┆         │
│ …                  ┆ …                 ┆ …         ┆ …         ┆ …         ┆ …         ┆ …       │
│ SAGGSATFYNFIMGFQND ┆ SAGGSATFYNFIMGFQN ┆ 2.108448  ┆ 4.507194  ┆ 2.398746  ┆ L25C      ┆ true    │
│ NTPFGICAEHVS…      ┆ DNTPFGILAEHVS…    ┆           ┆           ┆           ┆           ┆         │
│ SAGGSAGGKFNKELSVAG ┆ SAGGSAGGKFNKELSVA ┆ 1.994101  ┆ 1.737462  ┆ -0.25664  ┆ E20W      ┆ true    │
│ RWIVTLPNLNDP…      ┆ GREIVTLPNLNDP…    ┆           ┆           ┆           ┆           ┆         │
│ SAGGAQASVVANQLIPIN ┆ SAGGAQASVVANQLIPI ┆ 6.133186  ┆ 6.068468  ┆ -0.064718 ┆ T22Q      ┆ true    │
│ TYLQLVMMRSEV…      ┆ NTYLTLVMMRSEV…    ┆           ┆           ┆           ┆           ┆         │
│ SAGGSAAIERGSKFKILR ┆ SAGGSAAIERGSKVKIL ┆ -0.303636 ┆ 1.711096  ┆ 2.014732  ┆ V14F:L71R ┆ true    │
│ KESYWYGDVGTV…      ┆ RKESYWYGDVGTV…    ┆           ┆           ┆           ┆           ┆         │
│ SAGGSAVSDRLIGRKGVV ┆ SAGGSAVSDRLIGRKGV ┆ 4.29628   ┆ 4.80547   ┆ 0.50919   ┆ K54N      ┆ true    │
│ MEAISPQNSGLV…      ┆ VMEAISPQNSGLV…    ┆           ┆           ┆           ┆           ┆         │
└────────────────────┴───────────────────┴───────────┴───────────┴───────────┴───────────┴─────────┘

In [2]:
df["ddG"].describe()

shape: (9, 2)
┌────────────┬─────────────┐
│ statistic  ┆ value       │
│ ---        ┆ ---         │
│ str        ┆ f64         │
╞════════════╪═════════════╡
│ count      ┆ 833828.0    │
│ null_count ┆ 0.0         │
│ mean       ┆ -2.6042e-17 │
│ std        ┆ 2.46046     │
│ min        ┆ -17.674774  │
│ 25%        ┆ -0.962962   │
│ 50%        ┆ 0.000002    │
│ 75%        ┆ 0.962962    │
│ max        ┆ 17.674774   │
└────────────┴─────────────┘

In [7]:
k_neg = 0.261
k_pos = 0.261
A_neg = 1.0
A_pos = 1.0

sigmoid_expr = (
    pl.when(pl.col("ddG") >= 0)
    .then(A_pos * (2 / (1 + (-k_pos * pl.col("ddG")).exp()) - 1))
    .otherwise(-A_neg * (2 / (1 + (-k_neg * (-pl.col("ddG"))).exp()) - 1))
)

df = df.with_columns(
    sigmoid_expr.alias("normalized_ddG_sigmoid")
)

df = df.with_columns(
    (pl.col("normalized_ddG_sigmoid")*-1) .alias("normalized_stability")
)
df.write_csv("datasets/megascale_dataset_with_ddg_normalized.csv")
df

shape: (833_828, 9)
┌────────────┬───────────┬───────────┬───────────┬───┬───────────┬─────────┬───────────┬───────────┐
│ original_s ┆ mutated_s ┆ deltaG    ┆ deltaG_wt ┆ … ┆ mut_type  ┆ reverse ┆ normalize ┆ normalize │
│ eq_full    ┆ eq_full   ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---     ┆ d_ddG_sig ┆ d_stabili │
│ ---        ┆ ---       ┆ f64       ┆ f64       ┆   ┆ str       ┆ bool    ┆ moid      ┆ ty        │
│ str        ┆ str       ┆           ┆           ┆   ┆           ┆         ┆ ---       ┆ ---       │
│            ┆           ┆           ┆           ┆   ┆           ┆         ┆ f64       ┆ f64       │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═════════╪═══════════╪═══════════╡
│ GGGLPEGWEM ┆ GGGTPEGWE ┆ -0.369388 ┆ 1.362971  ┆ … ┆ L4T       ┆ false   ┆ -0.222299 ┆ 0.222299  │
│ RFTVDGIPYF ┆ MRFTVDGIP ┆           ┆           ┆   ┆           ┆         ┆           ┆           │
│ VDHNRRTTTY ┆ YFVDHNRRT ┆           ┆           ┆   ┆           ┆         ┆           ┆           │
│ …          ┆ TTY…      ┆           ┆           ┆   ┆           ┆         ┆           ┆           │
│ SAGGSAGGSA ┆ SAGGSAGGS ┆ 3.299296  ┆ 3.642546  ┆ … ┆ N33E      ┆ false   ┆ -0.044764 ┆ 0.044764  │
│ GGVDNKFNKE ┆ AGGVDNKFN ┆           ┆           ┆   ┆           ┆         ┆           ┆           │
│ QQNAFYEILH ┆ KEQQNAFYE ┆           ┆           ┆   ┆           ┆         ┆           ┆           │
│ …          ┆ ILH…      ┆           ┆           ┆   ┆           ┆         ┆           ┆           │
│ SAGMEQATVK ┆ SAGMEQATV ┆ -0.116898 ┆ 1.873137  ┆ … ┆ Q62D      ┆ false   ┆ -0.254014 ┆ 0.254014  │
│ WFNAEKGFGF ┆ KWFNAEKGF ┆           ┆           ┆   ┆           ┆         ┆           ┆           │
│ IERENGDDVF ┆ GFIERENGD ┆           ┆           ┆   ┆           ┆         ┆           ┆           │
│ …          ┆ DVF…      ┆           ┆           ┆   ┆           ┆         ┆           ┆           │
│ SAGGSAGGNQ ┆ SAGGSAGGN ┆ 6.390221  ┆ 5.703114  ┆ … ┆ I40L:L48Y ┆ false   ┆ 0.089428  ┆ -0.089428 │
│ ASVVANQLIP ┆ QASVVANQL ┆           ┆           ┆   ┆           ┆         ┆           ┆           │
│ INTALTLVMM ┆ IPINTALTL ┆           ┆           ┆   ┆           ┆         ┆           ┆           │
│ …          ┆ VMM…      ┆           ┆           ┆   ┆           ┆         ┆           ┆           │
│ SAGGSAGGTV ┆ SAGGSAGGT ┆ 4.645758  ┆ 4.220052  ┆ … ┆ V52I      ┆ false   ┆ 0.055498  ┆ -0.055498 │
│ KFKYKGEEKQ ┆ VKFKYKGEE ┆           ┆           ┆   ┆           ┆         ┆           ┆           │
│ VDISKIKKVW ┆ KQVDISKIK ┆           ┆           ┆   ┆           ┆         ┆           ┆           │
│ …          ┆ KVW…      ┆           ┆           ┆   ┆           ┆         ┆           ┆           │
│ …          ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …       ┆ …         ┆ …         │
│ SAGGSATFYN ┆ SAGGSATFY ┆ 2.108448  ┆ 4.507194  ┆ … ┆ L25C      ┆ true    ┆ 0.303197  ┆ -0.303197 │
│ FIMGFQNDNT ┆ NFIMGFQND ┆           ┆           ┆   ┆           ┆         ┆           ┆           │
│ PFGICAEHVS ┆ NTPFGILAE ┆           ┆           ┆   ┆           ┆         ┆           ┆           │
│ …          ┆ HVS…      ┆           ┆           ┆   ┆           ┆         ┆           ┆           │
│ SAGGSAGGKF ┆ SAGGSAGGK ┆ 1.994101  ┆ 1.737462  ┆ … ┆ E20W      ┆ true    ┆ -0.033479 ┆ 0.033479  │
│ NKELSVAGRW ┆ FNKELSVAG ┆           ┆           ┆   ┆           ┆         ┆           ┆           │
│ IVTLPNLNDP ┆ REIVTLPNL ┆           ┆           ┆   ┆           ┆         ┆           ┆           │
│ …          ┆ NDP…      ┆           ┆           ┆   ┆           ┆         ┆           ┆           │
│ SAGGAQASVV ┆ SAGGAQASV ┆ 6.133186  ┆ 6.068468  ┆ … ┆ T22Q      ┆ true    ┆ -0.008446 ┆ 0.008446  │
│ ANQLIPINTY ┆ VANQLIPIN ┆           ┆           ┆   ┆           ┆         ┆           ┆           │
│ LQLVMMRSEV ┆ TYLTLVMMR ┆           ┆           ┆   ┆           ┆         ┆           ┆           │
│ …          ┆ SEV…      ┆           ┆           ┆   ┆           ┆         ┆           ┆           │
│ SAGGSAAIER ┆ SAGGSAAIE ┆ -0.303636 ┆ 1.711096  ┆ … ┆ V14F:L71R ┆ true    ┆ 0.257027  ┆ -0.257027 │
│ GSKFKILRKE ┆ RGSKVKILR ┆           ┆           ┆   ┆           ┆         ┆           ┆           │
│ SYWYGDVGTV ┆ KESYWYGDV ┆           ┆           ┆   ┆           ┆         ┆           ┆           │
│ …          ┆ GTV…      ┆           ┆           ┆   ┆           ┆         ┆           ┆           │
│ SAGGSAVSDR ┆ SAGGSAVSD ┆ 4.29628   ┆ 4.80547   ┆ … ┆ K54N      ┆ true    ┆ 0.066352  ┆ -0.066352 │
│ LIGRKGVVME ┆ RLIGRKGVV ┆           ┆           ┆   ┆           ┆         ┆           ┆           │
│ AISPQNSGLV ┆ MEAISPQNS ┆           ┆           ┆   ┆           ┆         ┆           ┆           │
│ …          ┆ GLV…      ┆           ┆           ┆   ┆           ┆         ┆           ┆           │
└────────────┴───────────┴───────────┴───────────┴───┴───────────┴─────────┴───────────┴───────────┘

In [4]:
df["normalized_ddG_sigmoid"].describe()

shape: (9, 2)
┌────────────┬────────────┐
│ statistic  ┆ value      │
│ ---        ┆ ---        │
│ str        ┆ f64        │
╞════════════╪════════════╡
│ count      ┆ 833828.0   │
│ null_count ┆ 0.0        │
│ mean       ┆ 8.0102e-18 │
│ std        ┆ 0.274199   │
│ min        ┆ -0.980353  │
│ 25%        ┆ -0.125009  │
│ 50%        ┆ 2.1026e-7  │
│ 75%        ┆ 0.125009   │
│ max        ┆ 0.980353   │
└────────────┴────────────┘

In [5]:
df.filter(pl.col('original_seq_full') == pl.col('mutated_seq_full'))

shape: (0, 9)
┌─────────────┬────────────┬────────┬───────────┬───┬──────────┬─────────┬────────────┬────────────┐
│ original_se ┆ mutated_se ┆ deltaG ┆ deltaG_wt ┆ … ┆ mut_type ┆ reverse ┆ normalized ┆ normalized │
│ q_full      ┆ q_full     ┆ ---    ┆ ---       ┆   ┆ ---      ┆ ---     ┆ _ddG_sigmo ┆ _stability │
│ ---         ┆ ---        ┆ f64    ┆ f64       ┆   ┆ str      ┆ bool    ┆ id         ┆ ---        │
│ str         ┆ str        ┆        ┆           ┆   ┆          ┆         ┆ ---        ┆ f64        │
│             ┆            ┆        ┆           ┆   ┆          ┆         ┆ f64        ┆            │
╞═════════════╪════════════╪════════╪═══════════╪═══╪══════════╪═════════╪════════════╪════════════╡
└─────────────┴────────────┴────────┴───────────┴───┴──────────┴─────────┴────────────┴────────────┘

In [6]:
len(unique_seqs_lehner)

NameError: name 'unique_seqs_lehner' is not defined