In [1]:
import polars as pl

DATASET_FILE_NAME = "datasets/dataset_merged"
DATASET_FILE_NAME_WITH_FAMILIES = "datasets/dataset_merged_with_families"

df_lehner = pl.read_csv(
    "lehner_dataset_with_sequences_normalized.csv",
)
df_lehner = df_lehner.drop_nulls(
    subset=["original_seq_full", "mut_type", "mutated_seq_full", "normalized_fitness_sigmoid"])

df_lehner = df_lehner.with_columns(
    [
        pl.lit("lehner").alias("data_source"),
    ]
)

df_lehner = df_lehner.rename({"normalized_fitness_sigmoid": "target"})

df_lehner = df_lehner.select(["original_seq_full", "mutated_seq_full", "mut_type", "target", "reverse", "data_source"])

df_lehner

shape: (1_116_004, 6)
┌─────────────────────────┬─────────────────────────┬──────────┬───────────┬─────────┬─────────────┐
│ original_seq_full       ┆ mutated_seq_full        ┆ mut_type ┆ target    ┆ reverse ┆ data_source │
│ ---                     ┆ ---                     ┆ ---      ┆ ---       ┆ ---     ┆ ---         │
│ str                     ┆ str                     ┆ str      ┆ f64       ┆ bool    ┆ str         │
╞═════════════════════════╪═════════════════════════╪══════════╪═══════════╪═════════╪═════════════╡
│ M*IFVKTLMGKTITLEVELSDTI ┆ MQIFVKTLMGKTITLEVELSDTI ┆ Q2*      ┆ 0.342301  ┆ true    ┆ lehner      │
│ DNVKAKI…                ┆ DNVKAKI…                ┆          ┆           ┆         ┆             │
│ MAIFVKTLMGKTITLEVELSDTI ┆ MQIFVKTLMGKTITLEVELSDTI ┆ Q2A      ┆ 0.121678  ┆ true    ┆ lehner      │
│ DNVKAKI…                ┆ DNVKAKI…                ┆          ┆           ┆         ┆             │
│ MCIFVKTLMGKTITLEVELSDTI ┆ MQIFVKTLMGKTITLEVELSDTI ┆ Q2C      ┆ 0.044935  ┆ true    ┆ lehner      │
│ DNVKAKI…                ┆ DNVKAKI…                ┆          ┆           ┆         ┆             │
│ MDIFVKTLMGKTITLEVELSDTI ┆ MQIFVKTLMGKTITLEVELSDTI ┆ Q2D      ┆ 0.11189   ┆ true    ┆ lehner      │
│ DNVKAKI…                ┆ DNVKAKI…                ┆          ┆           ┆         ┆             │
│ MEIFVKTLMGKTITLEVELSDTI ┆ MQIFVKTLMGKTITLEVELSDTI ┆ Q2E      ┆ -0.162632 ┆ true    ┆ lehner      │
│ DNVKAKI…                ┆ DNVKAKI…                ┆          ┆           ┆         ┆             │
│ …                       ┆ …                       ┆ …        ┆ …         ┆ …       ┆ …           │
│ MGNEASLEGEGLPEGLAAAAAAG ┆ MGNEASLEGEGLPEGLAAAAAAG ┆ V1059C   ┆ -0.45026  ┆ false   ┆ lehner      │
│ GGASGAG…                ┆ GGASGAG…                ┆          ┆           ┆         ┆             │
│ MGNEASLEGEGLPEGLAAAAAAG ┆ MGNEASLEGEGLPEGLAAAAAAG ┆ W1059C   ┆ -0.374472 ┆ false   ┆ lehner      │
│ GGASGAG…                ┆ GGASGAG…                ┆          ┆           ┆         ┆             │
│ MGNEASLEGEGLPEGLAAAAAAG ┆ MGNEASLEGEGLPEGLAAAAAAG ┆ Y1059C   ┆ -0.462593 ┆ false   ┆ lehner      │
│ GGASGAG…                ┆ GGASGAG…                ┆          ┆           ┆         ┆             │
│ MGNEASLEGEGLPEGLAAAAAAG ┆ MGNEASLEGEGLPEGLAAAAAAG ┆ V1058T   ┆ -0.087532 ┆ false   ┆ lehner      │
│ GGASGAG…                ┆ GGASGAG…                ┆          ┆           ┆         ┆             │
│ MGNEASLEGEGLPEGLAAAAAAG ┆ MGNEASLEGEGLPEGLAAAAAAG ┆ W1058T   ┆ -0.220831 ┆ false   ┆ lehner      │
│ GGASGAG…                ┆ GGASGAG…                ┆          ┆           ┆         ┆             │
└─────────────────────────┴─────────────────────────┴──────────┴───────────┴─────────┴─────────────┘

In [2]:
df_megascale = pl.read_csv(
    "megascale_dataset_with_ddg_normalized.csv",
)

df_megascale = df_megascale.drop_nulls(
    subset=["original_seq_full", "mut_type", "mutated_seq_full", "normalized_ddG_sigmoid"])

df_megascale = df_megascale.with_columns(
    [
        pl.lit("megascale").alias("data_source"),
    ]
)

df_megascale = df_megascale.rename({"normalized_ddG_sigmoid": "target"})

df_megascale = df_megascale.select(
    ["original_seq_full", "mutated_seq_full", "mut_type", "target", "reverse", "data_source"])

df_megascale

shape: (833_828, 6)
┌─────────────────────────┬────────────────────────┬───────────┬───────────┬─────────┬─────────────┐
│ original_seq_full       ┆ mutated_seq_full       ┆ mut_type  ┆ target    ┆ reverse ┆ data_source │
│ ---                     ┆ ---                    ┆ ---       ┆ ---       ┆ ---     ┆ ---         │
│ str                     ┆ str                    ┆ str       ┆ f64       ┆ bool    ┆ str         │
╞═════════════════════════╪════════════════════════╪═══════════╪═══════════╪═════════╪═════════════╡
│ SAGGTYTWNTKEEAKQAFKELLK ┆ SAGGTYTWNTKEEAKQAFKELL ┆ R22P      ┆ -0.209184 ┆ false   ┆ megascale   │
│ EKRVPSN…                ┆ KEKPVPSN…              ┆           ┆           ┆         ┆             │
│ SAGGSAGGSAGGHEITLHINGRR ┆ SAGGSAGGSAGGHEITLHINGR ┆ R17T      ┆ -0.110833 ┆ false   ┆ megascale   │
│ VKLRFRD…                ┆ RVKLRFTD…              ┆           ┆           ┆         ┆             │
│ SAGGSAGGSKDPKFEAAYDFPGS ┆ SAGGSAGGSKDPKFEAAMDFPG ┆ Y9M:K24Q  ┆ -0.151356 ┆ false   ┆ megascale   │
│ GSSSELP…                ┆ SGSSSELP…              ┆           ┆           ┆         ┆             │
│ SAGGNKASVVANQLIPINTALTL ┆ SAGGNKASVVANQLIPINTALT ┆ K39N      ┆ -0.038819 ┆ false   ┆ megascale   │
│ IMMKAEV…                ┆ LIMMKAEV…              ┆           ┆           ┆         ┆             │
│ SAGGSAGWVPTKREEKYGVAFYN ┆ SAGGSAGWVPTKREEKYGVAFY ┆ D31M:T47G ┆ -0.187832 ┆ false   ┆ megascale   │
│ YDARGAD…                ┆ NYDARGAD…              ┆           ┆           ┆         ┆             │
│ …                       ┆ …                      ┆ …         ┆ …         ┆ …       ┆ …           │
│ SAGGNQASVVANQLIPINTALTL ┆ SAGGNQASVVANQLIPINTALT ┆ V26E      ┆ -0.13243  ┆ true    ┆ megascale   │
│ VMMRSEE…                ┆ LVMMRSEV…              ┆           ┆           ┆         ┆             │
│ SAGGSAGGSAQGDIVVALYPEDG ┆ SAGGSAGGSAQGDIVVALYPYD ┆ Y11E:Y54I ┆ 0.604106  ┆ true    ┆ megascale   │
│ IHPDDLS…                ┆ GIHPDDLS…              ┆           ┆           ┆         ┆             │
│ SAGGSAGGMTYKLILNGKTLKGE ┆ SAGGSAGGMTYKLILNGKTLKG ┆ D47K      ┆ 0.091188  ┆ true    ┆ megascale   │
│ TTTEAVD…                ┆ ETTTEAVD…              ┆           ┆           ┆         ┆             │
│ GSQPHIGNTTFTFDNPEKAQKYA ┆ GSQVHIGNTTFTFDNPEKAQKY ┆ V3P       ┆ 0.1783    ┆ true    ┆ megascale   │
│ EKYAKKK…                ┆ AEKYAKKK…              ┆           ┆           ┆         ┆             │
│ SAGGSAGGMVQRGSKVRILRPES ┆ SAGGSAGGMVQRGSKVRILRPE ┆ E41P:K42M ┆ 0.249009  ┆ true    ┆ megascale   │
│ YWFQDVG…                ┆ SYWFQDVG…              ┆           ┆           ┆         ┆             │
└─────────────────────────┴────────────────────────┴───────────┴───────────┴─────────┴─────────────┘

In [3]:
df_merged = pl.concat([df_megascale, df_lehner])
df_merged

shape: (1_949_832, 6)
┌─────────────────────────┬────────────────────────┬───────────┬───────────┬─────────┬─────────────┐
│ original_seq_full       ┆ mutated_seq_full       ┆ mut_type  ┆ target    ┆ reverse ┆ data_source │
│ ---                     ┆ ---                    ┆ ---       ┆ ---       ┆ ---     ┆ ---         │
│ str                     ┆ str                    ┆ str       ┆ f64       ┆ bool    ┆ str         │
╞═════════════════════════╪════════════════════════╪═══════════╪═══════════╪═════════╪═════════════╡
│ SAGGTYTWNTKEEAKQAFKELLK ┆ SAGGTYTWNTKEEAKQAFKELL ┆ R22P      ┆ -0.209184 ┆ false   ┆ megascale   │
│ EKRVPSN…                ┆ KEKPVPSN…              ┆           ┆           ┆         ┆             │
│ SAGGSAGGSAGGHEITLHINGRR ┆ SAGGSAGGSAGGHEITLHINGR ┆ R17T      ┆ -0.110833 ┆ false   ┆ megascale   │
│ VKLRFRD…                ┆ RVKLRFTD…              ┆           ┆           ┆         ┆             │
│ SAGGSAGGSKDPKFEAAYDFPGS ┆ SAGGSAGGSKDPKFEAAMDFPG ┆ Y9M:K24Q  ┆ -0.151356 ┆ false   ┆ megascale   │
│ GSSSELP…                ┆ SGSSSELP…              ┆           ┆           ┆         ┆             │
│ SAGGNKASVVANQLIPINTALTL ┆ SAGGNKASVVANQLIPINTALT ┆ K39N      ┆ -0.038819 ┆ false   ┆ megascale   │
│ IMMKAEV…                ┆ LIMMKAEV…              ┆           ┆           ┆         ┆             │
│ SAGGSAGWVPTKREEKYGVAFYN ┆ SAGGSAGWVPTKREEKYGVAFY ┆ D31M:T47G ┆ -0.187832 ┆ false   ┆ megascale   │
│ YDARGAD…                ┆ NYDARGAD…              ┆           ┆           ┆         ┆             │
│ …                       ┆ …                      ┆ …         ┆ …         ┆ …       ┆ …           │
│ MGNEASLEGEGLPEGLAAAAAAG ┆ MGNEASLEGEGLPEGLAAAAAA ┆ V1059C    ┆ -0.45026  ┆ false   ┆ lehner      │
│ GGASGAG…                ┆ GGGASGAG…              ┆           ┆           ┆         ┆             │
│ MGNEASLEGEGLPEGLAAAAAAG ┆ MGNEASLEGEGLPEGLAAAAAA ┆ W1059C    ┆ -0.374472 ┆ false   ┆ lehner      │
│ GGASGAG…                ┆ GGGASGAG…              ┆           ┆           ┆         ┆             │
│ MGNEASLEGEGLPEGLAAAAAAG ┆ MGNEASLEGEGLPEGLAAAAAA ┆ Y1059C    ┆ -0.462593 ┆ false   ┆ lehner      │
│ GGASGAG…                ┆ GGGASGAG…              ┆           ┆           ┆         ┆             │
│ MGNEASLEGEGLPEGLAAAAAAG ┆ MGNEASLEGEGLPEGLAAAAAA ┆ V1058T    ┆ -0.087532 ┆ false   ┆ lehner      │
│ GGASGAG…                ┆ GGGASGAG…              ┆           ┆           ┆         ┆             │
│ MGNEASLEGEGLPEGLAAAAAAG ┆ MGNEASLEGEGLPEGLAAAAAA ┆ W1058T    ┆ -0.220831 ┆ false   ┆ lehner      │
│ GGASGAG…                ┆ GGGASGAG…              ┆           ┆           ┆         ┆             │
└─────────────────────────┴────────────────────────┴───────────┴───────────┴─────────┴─────────────┘

In [4]:
df_merged.write_parquet(f"{DATASET_FILE_NAME}.csv")

In [5]:
df_cath = pl.read_csv("../classification_dataset/dataset_with_families.csv")

lf_cath_prepared = (
    df_cath.lazy()
    .drop_nulls(subset=["cath_dominant"])
    .with_columns(
        pl.col("cath_dominant").str.split(".").alias("_split_temp")
    )
    .with_columns([
        pl.col("_split_temp").list.get(0).alias("cath_class"),  # C (Level 1)
        pl.col("_split_temp").list.get(1).alias("cath_arch"),  # A (Level 2)
        pl.col("_split_temp").list.get(2).alias("cath_topology"),  # T (Level 3)
        pl.col("_split_temp").list.get(3).alias("cath_homology"),  # H (Level 4)F
    ])
    # Vybereme jen to, co chceme poslat do joinu (včetně původního cath_dominant)
    .select([
        "original_seq_full",
        "cath_dominant",  # Původní sloupec
        "cath_all",  # Původní sloupec
        "cath_class",  # Nový
        "cath_arch",  # Nový
        "cath_topology",  # Nový
        "cath_homology"  # Nový
    ])
)

In [15]:

# droping the row with null cath_dominant
query = (
    df_merged.lazy()
    .join(
        other=(
            lf_cath_prepared
            .drop_nulls(subset=["cath_dominant"])
            .select(["original_seq_full", "cath_dominant", "cath_all",
                     "cath_class", "cath_arch", "cath_topology", "cath_homology"])
            .unique(subset=["original_seq_full"], keep="first")
        ),
        on="original_seq_full",
        how="left"
    )
    # Poznámka: Pokud zde dáte drop_nulls(), chová se to ve výsledku spíše jako INNER JOIN
    # (vyhodí to sekvence, které nemají CATH záznam).
    .drop_nulls().drop_nans()
)

# 3. Spustíme výpočet a streamujeme výsledek rovnou do souboru
query.sink_parquet(f"{DATASET_FILE_NAME_WITH_FAMILIES}.parquet")

In [17]:
import polars as pl
import gc

# 1. Cesta k vašemu velkému, již vytvořenému souboru
source_file = f"{DATASET_FILE_NAME_WITH_FAMILIES}.parquet"

# Definice úrovní
cath_levels = ["cath_class", "cath_arch", "cath_topology", "cath_homology"]
current_subset = []

print("Začínám paměťově úsporný výpočet...")

for level in cath_levels:
    # Přidáme aktuální úroveň do seskupení (postupně [C], [C, A], [C, A, T]...)
    current_subset.append(level)

    output_filename = f"datasets/stats_{level}.parquet"
    print(f"--- Zpracovávám úroveň: {current_subset} -> {output_filename} ---")

    # 2. Vytvoříme novou Lazy Query pro každý průchod
    # DŮLEŽITÉ: .select(current_subset) zajistí, že z disku čteme JEN to, co teď seskupujeme.
    # Ostatní sloupce se vůbec nenačtou do RAM.
    q = (
        pl.scan_parquet(source_file)
        .select(current_subset)
        .group_by(current_subset)
        .len()                # Spočítáme výskyty
        .sort("len", descending=True) # Seřadíme (to už je nad malými daty, to je OK)
    )

    # 3. ZÁPIS NA DISK (Místo .collect())
    # Toto je klíčové. Nepoužíváme collect(), ale sink_parquet().
    # Data protečou pamětí a hned zmizí na disk.
    q.sink_parquet(output_filename)

    # 4. Úklid
    print(f"Uloženo do {output_filename}")
    gc.collect() # Pro jistotu vynutíme úklid paměti v Pythonu

print("Hotovo. Všechny statistiky jsou uloženy v souborech stats_*.parquet")

Začínám paměťově úsporný výpočet...
--- Zpracovávám úroveň: ['cath_class'] -> datasets/stats_cath_class.parquet ---
Uloženo do datasets/stats_cath_class.parquet
--- Zpracovávám úroveň: ['cath_class', 'cath_arch'] -> datasets/stats_cath_arch.parquet ---
Uloženo do datasets/stats_cath_arch.parquet
--- Zpracovávám úroveň: ['cath_class', 'cath_arch', 'cath_topology'] -> datasets/stats_cath_topology.parquet ---
Uloženo do datasets/stats_cath_topology.parquet
--- Zpracovávám úroveň: ['cath_class', 'cath_arch', 'cath_topology', 'cath_homology'] -> datasets/stats_cath_homology.parquet ---
Uloženo do datasets/stats_cath_homology.parquet
Hotovo. Všechny statistiky jsou uloženy v souborech stats_*.parquet